### PR TITLE
Fixed display color

### LINKED ISSUE #5: fix display colour
Change the colours of the text or change the colour of the background to dark 

image

### PR DESCRIPTION
**Pull request by Yashs911**
Fixes #5

### CODE REVIEW

**Comment by Dishebh** [comment]
@Yashs911, please share the screenshots of the change or a preview link for the pr reflecting the changes.

**Comment by Yashs911** [comment]
@Dishebh 
vibhav
I cannot see the hover change but it will change the purple to blue

**Review by Dishebh — APPROVED** [review]

**Comment by Yuvraj-kadale** [comment]
@Yashs911  could you please change the colour ! 
keep the color scheme as 
image

Note: don't change the complete background of the website. 
just change the background of the first container

**Comment by Yashs911** [comment]
@Yuvraj-kadale Is this okay?
aa

**Comment by Vibhav-NITH** [comment]
@Yashs911 the Nav bar is getting cut!
try to keep it complete , and if possible you can add edge curves that will segment the two containers!

image

Do these changes and your PR will be good to go , Happy contributing :)

**Comment by Dishebh** [comment]
@Yashs911, any updates? :)

**Comment by Yashs911** [comment]
@Dishebh I am working on this. Sorry for the delay.

**Comment by Yashs911** [comment]
@Dishebh 
ss

**Review by Dishebh — APPROVED** [review]

**Review by Yuvraj-kadale — APPROVED** [review]

**Review by Vibhav-NITH — APPROVED** [review]

**Comment by Vibhav-NITH** [comment]
@Yashs911 Good job !!

**Pull request merged**
