### PR TITLE
Updated footer

### LINKED ISSUE #12: Update footer
Make relevant changes required in the footer section 
eg: remove unnecessary titles and add relevant titles and images 

image

### PR DESCRIPTION
**Pull request by Yashs911**
Fixes #12 

### What are the changes done?
Replaced
Armor -> vibhav and its logo
working hours-> active during fest NIMBUS
Couses-> removed the entire section
our gallery -> replaced the images with the images attached in workshop section (4)
News letter-> contact us

at last , in the bottom right corner and social media icons (fb, insta, twitter, etc) and hyperlink them

### Screenshots of the changes made
ss

### CODE REVIEW

**Comment by Vibhav-NITH** [comment]
@Yashs911 keep 8 images in our gallery section , and your PR will be good to go ! 👍

**Comment by Yashs911** [comment]
@Vibhav-NITH In the workshop section there are only 5 images. So....

**Comment by Yashs911** [comment]
@Vibhav-NITH updated title logo

**Comment by Yuvraj-kadale** [comment]
> 
> 
> @Vibhav-NITH In the workshop section there are only 5 images. So....

@Yashs911 you can repeat the images

**Comment by Yashs911** [comment]
@Vibhav-NITH Have made the required changes

**Pull request merged**
